export const exhibitionTypes: string[] = [
  "Agriculture & Forestry",
  "Animals & Pets",
  "Apparel & Clothing",
  "Arts & Crafts",
  "Auto & Automotive",
  "Baby, Kids & Maternity",
  "Banking & Finance",
  "Building & Construction",
  "Business Services",
  "Education & Training",
  "Electric & Electronics",
  "Entertainment & Media",
  "Environment & Waste",
  "Fashion & Beauty",
  "Food & Beverages",
  "Home & Office",
  "Hospitality",
  "IT & Technology",
  "Industrial Engineering",
  "Logistics & Transportation",
  "Medical & Pharma",
  "Miscellaneous",
  "Packing & Packaging",
  "Power & Energy",
  "Science & Research",
  "Security & Defense",
  "Telecommunication",
  "Travel & Tourism",
  "Wellness, Health & Fitness",
];

interface StatesProps {
  id: number;
  name: string;
}
export const statesAndUnionTerritories: StatesProps[] = [
  { id: 1, name: "andhrapradesh" },
  { id: 2, name: "arunachalpradesh" },
  { id: 3, name: "assam" },
  { id: 4, name: "bihar" },
  { id: 5, name: "chhattisgarh" },
  { id: 6, name: "goa" },
  { id: 7, name: "gujarat" },
  { id: 8, name: "haryana" },
  { id: 9, name: "himachalpradesh" },
  { id: 10, name: "jharkhand" },
  { id: 11, name: "karnataka" },
  { id: 12, name: "kerala" },
  { id: 13, name: "madhyapradesh" },
  { id: 14, name: "maharashtra" },
  { id: 15, name: "manipur" },
  { id: 16, name: "meghalaya" },
  { id: 17, name: "mizoram" },
  { id: 18, name: "nagaland" },
  { id: 19, name: "odisha" },
  { id: 20, name: "punjab" },
  { id: 21, name: "rajasthan" },
  { id: 22, name: "sikkim" },
  { id: 23, name: "tamilnadu" },
  { id: 24, name: "telangana" },
  { id: 25, name: "tripura" },
  { id: 26, name: "uttarakhand" },
  { id: 27, name: "uttarpradesh" },
  { id: 28, name: "westbengal" },
  { id: 29, name: "andamanandnicobarislands" },
  { id: 30, name: "chandigarh" },
  { id: 31, name: "dadranagarhaveli" },
  { id: 32, name: "damandiu" },
  { id: 33, name: "delhincr" },
  { id: 34, name: "jammuandkashmir" },
  { id: 35, name: "ladakh" },
  { id: 36, name: "lakshadweep" },
  { id: 37, name: "puducherry" },
];

export const months: string[] = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const years: string[] = [
  "2024",
  "2025",
  "2026",
  "2027",
  "2028",
  "2029",
  "2030",
  "2031",
  "2032",
  "2033",
  "2034",
];

export const eventTypes = ["Exhibition"];
interface CompanyTypesProps {
  id: number;
  name: string;
}

export const companyTypes: CompanyTypesProps[] = [
  { id: 1, name: "Exhibition Organizer" },
  { id: 2, name: "Professional Conference Organiser (PCO)" },
  { id: 3, name: "Assoaication" },
  { id: 4, name: "Audio & Visual (AV)" },
  { id: 5, name: "Custom Stall Construction" },
  { id: 6, name: "Stand Contracter" },
  { id: 7, name: "Registration Service" },
  { id: 8, name: "Event Production" },
  { id: 9, name: "Kit Bag Manufacturer" },
  { id: 10, name: "Event Management" },
  { id: 11, name: "Manpower Agency" },
  { id: 12, name: "Outdoor Catering" },
  { id: 13, name: "Logistics" },
  { id: 14, name: "Wi-Fi Services" },
  { id: 15, name: "Filming & Photography" },
  { id: 16, name: "Event Manager" },
];

export const associationTypes: string[] = [
  "National Association",
  "State Chapter / Branch",
  "State Association",
];

export const segmentTypes: string[] = [
  "Anaesthesiology",
  "Orthopedics",
  "Dermatology",
  "Cardiology",
  "Psychiatrist",
  "Gastroenterology",
  "ENT",
  "Obstetrics & Gynecology",
  "Neurology",
  "Urology",
  "Dentist",
  "Diabetes Endocrinology",
  "Ophthalmology",
  "General Surgery",
  "Infectious Diseases",
  "Internal Medicine",
  "Nutrition",
  "Nephrology",
  "Paediatrica & Neonatology",
  "Pathology",
  "Radiology",
];
