export const exhibitionTypes: string[] = [
  "Agriculture & Forestry",
  "Animals & Pets",
  "Apparel & Clothing",
  "Arts & Crafts",
  "Auto & Automotive",
  "Baby, Kids & Maternity",
  "Banking & Finance",
  "Building & Construction",
  "Business Services",
  "Education & Training",
  "Electric & Electronics",
  "Entertainment & Media",
  "Environment & Waste",
  "Fashion & Beauty",
  "Food & Beverages",
  "Home & Office",
  "Hospitality",
  "IT & Technology",
  "Industrial Engineering",
  "Logistics & Transportation",
  "Medical & Pharma",
  "Miscellaneous",
  "Packing & Packaging",
  "Power & Energy",
  "Science & Research",
  "Security & Defense",
  "Telecommunication",
  "Travel & Tourism",
  "Wellness, Health & Fitness",
];

export const statesAndUnionTerritories: string[] = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi NCR",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];

export const months: string[] = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const years: string[] = [
  "2024",
  "2025",
  "2026",
  "2027",
  "2028",
  "2029",
  "2030",
  "2031",
  "2032",
  "2033",
  "2034",
];

export const eventTypes = ["Exhibition"];

export const companyTypes: string[] = [
  "Exhibition Organizer",
  "Professional Conference Organiser (PCO)",
  "Assoaication",
  "Audio & Visual (AV)",
  "Custom Stall Construction",
  "Stand Contracter",
  "Registration Service",
  "Event Production",
  "Kit Bag Manufacturer",
  "Event Management",
  "Manpower Agency",
  "Outdoor Catering",
  "Logistics",
  "Wi-Fi Services",
  "Filming & Photography",
  "Event Manager",
];

export const associationTypes: string[] = [
  "National Association",
  "State Chapter / Branch",
  "State Association",
];

export const segmentTypes: string[] = [
  "Anaesthesiology",
  "Orthopedics",
  "Dermatology",
  "Cardiology",
  "Psychiatrist",
  "Gastroenterology",
  "ENT",
  "Obstetrics & Gynecology",
  "Neurology",
  "Urology",
  "Dentist",
  "Diabetes Endocrinology",
  "Ophthalmology",
  "General Surgery",
  "Infectious Diseases",
  "Internal Medicine",
  "Nutrition",
  "Nephrology",
  "Paediatrica & Neonatology",
  "Pathology",
  "Radiology",
];
